apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.mongod.name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
  name: {{ .Values.replicas.name }}-{{ .Release.Name }}-mongodb
data:
  mongod.conf: |
{{ toYaml .Values.configmap | indent 4 }}
