# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ template "mongo.name" .}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "service.name" .}}-{{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: peer
      port: {{ .Values.global.port }}
  selector:
    app: {{ template "mongo.name" .}}
    release: {{ .Release.Name }}
