apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.mongos.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.mongos.name }}-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mongos.name }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicas.num }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongos.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.mongos.name }}
          image: "{{ .Values.global.mongoImage.repository }}:{{ .Values.global.mongoImage.tag }}"
          imagePullPolicy: "{{ .Values.global.mongoImage.pullPolicy }}"
          ports:
            - name: peer
              containerPort: {{ .Values.global.port }}
          command:
            - /init/on-start.sh
          args:
            - --configdb={{ template "cfgsvr.list" . }}
            - --port={{ .Values.global.port }}
            - --bind_ip=0.0.0.0
          env:
            - name: SRV_PORT
              value: "{{ .Values.global.port }}"
          volumeMounts:
            - name: datadir
              mountPath: /data/db
            - name: workdir
              mountPath: /work-dir
            - name: shlst
              mountPath: /sh-lst
            - name: init
              mountPath: /init
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.mongos.name }}
            topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: workdir
          emptyDir: {}
        - name: datadir
          emptyDir: {}
        - name: shlst
          configMap:
            name: {{ .Values.mongos.name }}-{{ .Release.Name }}-sharding
        - name: init
          configMap:
            defaultMode: 0755
            name: {{ .Values.mongos.name }}-{{ .Release.Name }}-init
            
          
          
