global:
  namesapce: default
  port: "27017"
  mongod:
    name: md
    repName: rs
    repNum: "3"
  config:
    name: cfg
    repName: cs
    repNum: "3"
  installImage:
    repository: swr.cn-east-2.myhuaweicloud.com/huawei_cn2/mongodb-install
    tag: 0.6
    pullPolicy: IfNotPresent
  mongoImage:
    repository: 100.125.17.64:20202/hwofficial/mongo
    tag: 3.4
    pullPolicy: IfNotPresent
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    annotations:
      volume.beta.kubernetes.io/storage-class: sas
      volume.beta.kubernetes.io/storage-provisioner: flexvolume-huawei.com/fuxivol    
  readinessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
    

# value for mongos deployment  
mongos:
  name: mongos
  shardNum: 2

replicas:
  name: mongos
  num: 3

 
# config svr 
config:
  replicas:
    svr: configsvr

# sharding 0                   
replicas0:
  replicas:
    idx: "0"

# sharding 1      
replicas1:
  replicas:
    idx: "1"

#for range loop
loop8: 
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'

 
auth:
  enabled: false

